name: on release

on:

  release:
    types:
    - released

env:
  TEST: "test"

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    concurrency: nova-deploy-prod-nova-prod
    steps:
    - name: Clear Applications-tag file
      run: |-
        echo ${{ github.event.release.tag_name }}
        echo ${{ github.ref }}
        echo ${{ github.base_ref }}
        echo "${{ github.event.release }}"